export enum EPageIDs {
    HOME_PAGE = 'HOME_PAGE',
    ARTICLES_PAGE = 'ARTICLES_PAGE',
    FEED_ARTICLES_PAGE = 'FEED_ARTICLES_PAGE',
    SAVED_ARTICLES_PAGE = 'SAVED_ARTICLES_PAGE',
    ARTICLE_DETAIL_PAGE = 'ARTICLE_DETAIL_PAGE',
    SETTINGS_PAGE = 'SETTINGS_PAGE'
}
